<a href="https://colab.research.google.com/github/chungntu/1DCNN-LSTM-ResNet/blob/main/Problem_1_Spring_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# ===============================
# Bài 1: Hệ phần tử lò xo
# ===============================

import numpy as np

# Kết nối giữa các nút cho từng phần tử
element_nodes = np.array([[1, 2], [2, 3], [2, 4]], dtype=int)

number_elements = element_nodes.shape[0]
number_nodes = 4

# Khởi tạo vectơ chuyển vị, vectơ lực và ma trận độ cứng
displacements = np.zeros((number_nodes, 1), dtype=float)
force = np.zeros((number_nodes, 1), dtype=float)
stiffness = np.zeros((number_nodes, number_nodes), dtype=float)

# Tải trọng tác dụng tại nút 2
# Lưu ý Python đánh chỉ số từ 0
force[1, 0] = 10.0

# Ma trận độ cứng phần tử
K_local = np.array([[ 1.0, -1.0],
                    [-1.0,  1.0]])

# Lắp ghép ma trận độ cứng tổng thể
for e in range(number_elements):
    dof = element_nodes[e] - 1
    i, j = dof[0], dof[1]
    stiffness[np.ix_([i, j], [i, j])] += K_local

# Các bậc tự do 1, 3, 4 cố định
# Lưu ý Python đánh chỉ số từ 0
fixed_dof = np.array([0, 2, 3])

all_dof = np.arange(number_nodes)

# active_dof là các bậc tự do có thể di chuyển
active_dof = np.setdiff1d(all_dof, fixed_dof)

# Giải hệ phương trình chỉ xét active_dof
stiffness_active_dof = stiffness[np.ix_(active_dof, active_dof)]
force_active_dof  = force[active_dof, :]
displacements_active_dof = np.linalg.solve(stiffness_active_dof, force_active_dof)

# Cập nhật kết quả vào vectơ chuyển vị tổng thể
displacements[active_dof, :] = displacements_active_dof

# Tính phản lực liên kết
reactions = stiffness @ displacements - force

# ===== Kết quả đầu ra =====
print("Ma trận độ cứng tổng thể:\n", stiffness)
print("\nVectơ lực:\n", force)
print("\n Vectơ chuyển vị:\n", displacements)
print("\nPhản lực:\n", reactions)


Ma trận độ cứng tổng thể:
 [[ 1. -1.  0.  0.]
 [-1.  3. -1. -1.]
 [ 0. -1.  1.  0.]
 [ 0. -1.  0.  1.]]

Vectơ lực:
 [[ 0.]
 [10.]
 [ 0.]
 [ 0.]]

 Vectơ chuyển vị:
 [[0.        ]
 [3.33333333]
 [0.        ]
 [0.        ]]

Phản lực:
 [[-3.33333333]
 [ 0.        ]
 [-3.33333333]
 [-3.33333333]]


# New Section